# Generated by Django 5.0.6 on 2024-06-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Producto',
        ),
    ]
